"""Tier A: procedural programs with known ground truth.

Every sample was generated by a program we wrote, so recovery is scored against
the *program*, not merely the picture. This is the only tier where memorisation
and rule-learning separate cleanly, and it hosts the REPEAT length-generalisation
test (train n <= 4, test n = 16).

It is also the complexity instrument. Motifs are placed inside a bounding box and
`random_figure` recursively subdivides its box to place sub-figures, so raising
`depth` produces genuinely *hierarchical* drawings rather than merely more
strokes on top of each other. That distinction is the point: a flat set-diffusion
model degrades on stroke count, but a hierarchical one is supposed to degrade on
nesting depth instead, and only a generator that can vary the two independently
can tell you which is happening.
"""

from __future__ import annotations

import random
from typing import Callable

from ..isa.asm import assemble
from ..isa.spec import CANVAS, Tier
from ..isa.unroll import Unrollable, unroll

Program = bytes
Box = tuple[int, int, int, int]  # x0, y0, x1, y1, inclusive
FULL: Box = (0, 0, CANVAS - 1, CANVAS - 1)
MIN_BOX = 24  # below this a figure stops subdividing and emits a leaf motif
DELTA_MAX = 127  # REPEAT's dx/dy operand is i8; see `random_grid`

Motif = Callable[[random.Random, Box], str]


def _pt(rng: random.Random, box: Box) -> tuple[int, int]:
    x0, y0, x1, y1 = box
    return rng.randint(x0, x1), rng.randint(y0, y1)


def _inset(box: Box, pad: int) -> Box:
    x0, y0, x1, y1 = box
    pad = min(pad, (x1 - x0) // 3, (y1 - y0) // 3)
    return x0 + pad, y0 + pad, x1 - pad, y1 - pad


def random_polyline(rng: random.Random, box: Box) -> str:
    n = rng.randint(2, 8)
    lines = ["MOVE {} {}".format(*_pt(rng, box))]
    lines += ["LINE {} {}".format(*_pt(rng, box)) for _ in range(n)]
    return "\n".join(lines)


def random_curve(rng: random.Random, box: Box) -> str:
    pts = " ".join(str(v) for _ in range(3) for v in _pt(rng, box))
    return "MOVE {} {}\nCURVE ".format(*_pt(rng, box)) + pts


def random_burst(rng: random.Random, box: Box) -> str:
    cx, cy = _pt(rng, _inset(box, (box[2] - box[0]) // 4))
    out = []
    for _ in range(rng.randint(3, 6)):
        out.append(f"MOVE {cx} {cy}")
        out.append("LINE {} {}".format(*_pt(rng, box)))
    return "\n".join(out)


def random_disc(rng: random.Random, box: Box) -> str:
    x0, y0, x1, y1 = _inset(box, 4)
    r = max(2, min(x1 - x0, y1 - y0) // 2)
    return "MOVE {} {}\nCIRCLE ".format(*_pt(rng, (x0, y0, x1, y1))) + str(rng.randint(2, r))


def random_grid(rng: random.Random, box: Box, max_count: int = 4,
                min_count: int = 2) -> str:
    """A REPEAT motif. Its L0 expansion is `count` times longer, which is exactly
    the L0->L1 compression the model is supposed to discover.

    Step, cell size and origin are drawn independently of `count`. Deriving them
    from it, as the first version did, left exactly three distinct outputs for a
    fixed box -- so every sample that picked this motif collapsed onto one of
    three programs, which is where Tier A's train/val leak came from. The body is
    still a square: widening it would change what "recover REPEAT" means, and
    that is a design decision rather than a defect.

    `dx`/`dy` are the i8 DELTA operand, so `step` is capped at 127 rather than
    left to depend on the canvas being small enough.

    `min_count` exists for the length-generalisation test, which needs a corpus
    whose repeats are *all* long -- a `max_count=16` corpus drawing uniformly
    from [2, 16] is mostly short repeats and would report the trained regime
    back at you. `step` is derived from `span // count`, so raising either bound
    shrinks the grid rather than pushing it off the canvas.
    """
    x0, y0, x1, y1 = box
    count = rng.randint(max(2, min_count), max(2, min_count, max_count))
    horizontal = (x1 - x0) >= (y1 - y0)
    span = (x1 - x0) if horizontal else (y1 - y0)

    cross = (y1 - y0) if horizontal else (x1 - x0)

    # count-1 gaps of `step` plus one cell of `size` have to fit inside `span`.
    step = rng.randint(4, max(4, min(DELTA_MAX, span // count)))
    size = rng.randint(2, max(2, min(step - 1, span - step * (count - 1))))
    along = rng.randint(0, max(0, span - (step * (count - 1) + size)))
    across = rng.randint(0, max(0, cross - size))
    ox, oy = (x0 + along, y0 + across) if horizontal else (x0 + across, y0 + along)
    dx, dy = (step, 0) if horizontal else (0, step)
    return "\n".join(
        [
            f"REPEAT {count} {dx} {dy}",
            f"MOVE {ox} {oy}",
            f"LINE {ox + size} {oy}",
            f"LINE {ox + size} {oy + size}",
            f"LINE {ox} {oy + size}",
            f"LINE {ox} {oy}",
            "ENDREP",
        ]
    )


_L0_MOTIFS: tuple[Motif, ...] = (random_polyline, random_curve, random_burst, random_disc)


def _leaf_motifs(tier: Tier, max_repeat: int, min_repeat: int = 2) -> list[Motif]:
    motifs: list[Motif] = list(_L0_MOTIFS)
    if tier >= Tier.L1:
        motifs.append(
            lambda rng, box: random_grid(rng, box, max_count=max_repeat,
                                         min_count=min_repeat)
        )
    return motifs


def _subdivide(box: Box, k: int) -> list[Box]:
    x0, y0, x1, y1 = box
    xs = [x0 + (x1 - x0) * i // k for i in range(k + 1)]
    ys = [y0 + (y1 - y0) * i // k for i in range(k + 1)]
    return [
        (xs[i], ys[j], xs[i + 1], ys[j + 1])
        for i in range(k)
        for j in range(k)
    ]


def random_figure(
    rng: random.Random,
    box: Box,
    tier: Tier = Tier.L1,
    depth: int = 1,
    breadth: int = 3,
    max_repeat: int = 4,
    min_repeat: int = 2,
) -> str:
    """Place `breadth` children inside `box`; recurse until `depth` runs out."""
    leaves = _leaf_motifs(tier, max_repeat, min_repeat)
    x0, y0, x1, y1 = box
    if depth <= 0 or min(x1 - x0, y1 - y0) < MIN_BOX:
        return rng.choice(leaves)(rng, box)

    k = max(2, int(breadth**0.5 + 0.5))
    cells = _subdivide(box, k)
    rng.shuffle(cells)
    parts = []
    for cell in cells[: max(1, breadth)]:
        if rng.random() < 0.5 and min(cell[2] - cell[0], cell[3] - cell[1]) >= MIN_BOX:
            parts.append(
                random_figure(rng, cell, tier, depth - 1, breadth, max_repeat,
                              min_repeat)
            )
        else:
            parts.append(rng.choice(leaves)(rng, cell))
    return "\n".join(parts)


def sample(
    rng: random.Random,
    tier: Tier = Tier.L1,
    n_motifs: int = 4,
    depth: int = 0,
    breadth: int = 3,
    max_repeat: int = 4,
    min_repeat: int = 2,
    flatten: bool = False,
) -> Program:
    """`depth=0` gives flat drawings (motifs scattered over the whole canvas);
    `depth>=1` gives nested figures.

    `flatten` returns the program's **L0 trace** instead of the program: the
    same drawing with every `REPEAT` expanded into its copies. That is claim
    2's training corpus -- structure present in the geometry and absent from the
    alphabet -- and it is the one Tier A never had, because `Tier.L0` drops the
    repeat motif entirely and `Tier.L1` hands the model the opcode
    (`dm/isa/unroll.py`). Raises `Unrollable` rather than falling back to the
    L1 form: a corpus advertised as flat that quietly contains `REPEAT` bytes
    would make claim 2's number meaningless in exactly the way that cannot be
    seen from the number.
    """
    body = []
    if depth > 0:
        body.append(
            random_figure(rng, FULL, tier, depth, breadth, max_repeat, min_repeat)
        )
    else:
        leaves = _leaf_motifs(tier, max_repeat, min_repeat)
        for _ in range(rng.randint(1, max(1, n_motifs))):
            body.append(rng.choice(leaves)(rng, _inset(FULL, 16)))
    if rng.random() < 0.3:
        body.insert(0, f"WIDTH {rng.randint(1, 4)}")
    body.append("HALT")
    program = assemble("\n".join(body))
    if not flatten:
        return program
    flat = unroll(program)
    if flat is None:
        raise Unrollable(f"no exact flat trace for a {len(program)}-byte program")
    return flat


class Exhausted(RuntimeError):
    """The generator could not supply `n` distinct programs.

    Raised rather than returning a short list: silently shrinking a split would
    change the denominator of every metric computed from it.
    """


def dataset(
    n: int,
    seed: int = 0,
    unique: bool = True,
    exclude: frozenset[Program] | set[Program] = frozenset(),
    **kwargs,
) -> list[Program]:
    """`unique` and `exclude` are what make a split mean anything.

    Duplicates inside train inflate the effective epoch count on whatever the
    generator happens to repeat, and a val program that also appears in train is
    scored as generalisation while measuring recall. Both were real: 1,167
    duplicate train samples and a 7.0% val/train overlap, which biased
    bits/drawing -- the headline metric -- optimistically and by an unknown
    amount.
    """
    rng = random.Random(seed)
    if not unique:
        return [sample(rng, **kwargs) for _ in range(n)]

    seen, out = set(exclude), []
    # Rejection sampling needs a bound, and the bound has to be generous enough
    # that a legitimately narrow rung does not trip it on an unlucky seed.
    for _ in range(100 * n + 1000):
        try:
            program = sample(rng, **kwargs)
        except Unrollable:
            # A draw whose repeats have no exact flat trace. Rejected, not
            # clamped -- see `dm.isa.unroll`. It counts against the bound, so a
            # `flatten` corpus whose parameters make most draws unexpandable
            # raises `Exhausted` rather than quietly taking an hour.
            continue
        if program in seen:
            continue
        seen.add(program)
        out.append(program)
        if len(out) == n:
            return out
    raise Exhausted(
        f"only {len(out)}/{n} distinct programs for {kwargs or 'defaults'}; "
        "the motif entropy is too low for a split this size"
    )


def split(
    n_train: int, n_val: int, seed: int = 0, **kwargs
) -> tuple[list[Program], list[Program]]:
    """Train and val, both deduplicated and disjoint from each other.

    Val is drawn from a different stream *and* filtered against train, because a
    different seed alone does not make the splits disjoint -- it only makes the
    collisions harder to notice.
    """
    train = dataset(n_train, seed=seed, **kwargs)
    val = dataset(n_val, seed=seed + 10_000, exclude=frozenset(train), **kwargs)
    return train, val


#: Complexity ladder. Diffusion is expected to hold on the low rungs and break
#: somewhere up here; the point of having it before any model exists is to find
#: out *which* rung in week two rather than month four.
LADDER: dict[str, dict] = {
    "trivial": dict(n_motifs=1, depth=0),
    "simple": dict(n_motifs=4, depth=0),
    "busy": dict(n_motifs=16, depth=0),
    "nested": dict(depth=1, breadth=4),
    "deep": dict(depth=2, breadth=4),
    "elaborate": dict(depth=3, breadth=4),
}


def ladder(n: int = 256, seed: int = 0, tier: Tier = Tier.L1) -> dict[str, list[Program]]:
    return {
        rung: dataset(n, seed=seed + i, tier=tier, **kwargs)
        for i, (rung, kwargs) in enumerate(LADDER.items())
    }
